# Generated by Django 3.1.7 on 2021-02-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_recipes_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='Customers',
            new_name='customers',
        ),
        migrations.AddField(
            model_name='list',
            name='recipes',
            field=models.ManyToManyField(to='api.Recipes'),
        ),
    ]
